apiVersion: apps/v1
kind: Deployment
metadata:
  name: project4-depl
  labels:
    app: project4

spec:
  replicas: 2
  selector:
    matchLabels:
      app: project4

  template:
    metadata:
      labels:
        app: project4
    spec:
      containers:
        - name: project4
          image: semairem/project4:latest
          ports:
            - containerPort: 8080